### ISSUE TITLE
a doubt

### ISSUE THREAD

**Issue by n0g4y0** [crystalDf/CS-193A-Week-01-NumberGuessingGame#1]
hi crystal, can you have the material of de marty's course android 2019? refer: slides, coding files..etc
i saw him work with kotlin this year.

thanks so much, and i'm sorry for my bad english..

**Comment by crystalDf** [comment]
Hi,

The bad news is such files cannot be downloaded from the cs193a website for me either.
The good news is the course videos are uploaded to youtube and you can check them instead.

**Comment by n0g4y0** [comment]
thanks a lot for the info
